# Include the common Makefile
include ../.common/MakefileCommon

# The configurations applied by this profile. Example: "CONFIGS := nvim tmux zsh"
CONFIGS := nvim zellij

stow:
	$(COMMON_STOW_CMD) $(CONFIGS)
unstow:
	$(COMMON_UNSTOW_CMD) $(CONFIGS)
